name = "vitepress-better-demo-plugin"
compatibility_date = "2025-11-30"
pages_build_output_dir = "docs/.vitepress/dist"

[build]
command = "pnpm install --frozen-lockfile && pnpm --filter vitepress-better-demo-plugin build && pnpm -C docs docs:build"
